export type Locale = "ko" | "en";

export const dictionaries = {
  ko: {
    /* 공통 */
    appTitle: "무용한 기쁨",
    appDescription: "나를 기쁘게 하는 아름답지만 무용한 것은?",

    /* QuestionPhase */
    questionLine1: "나를 기쁘게 하는",
    questionLine2: "아름답지만",
    questionLine3: "무용한 것은?",
    answerPlaceholder: (n: number | null) =>
      n !== null ? `${n + 1}번째 당신의 생각을 적어주세요...` : "당신의 생각을 적어주세요...",
    nicknamePlaceholder: "닉네임을 입력하세요",
    nicknameRandom: "닉네임 랜덤",
    submit: "시작 >",
    submitHint: "Ctrl+Enter to submit",
    tickerLabel: "다른 사람들의 무용한 기쁨",
    archive: "아카이브",

    /* LoadingPhase */
    loading: "생각 적는중",

    /* ArtPhase */
    rewrite: "다시 쓰기",
    share: "공유하기",
    aiDisclaimer: "사용자가 입력한 답변을 바탕으로 AI가 작성한 문구입니다.",

    /* ArchivePhase */
    archiveLabel: "03 / ARCHIVE",
    archiveTitle1: "무용한 것들의",
    archiveTitle2: "아카이브",
    records: (n: number) => `${n} RECORDS`,
    noRecords: "아직 기록이 없습니다.",
    noRecordsHint: "첫 번째 답을 적어보세요.",
    firstRecord: "첫 기록 남기기 >",
    newWrite: "+ 새로 쓰기",
    goBack: "< 돌아가기",
    view: "보기 >",

    /* PixelModal */
    deleteConfirm: "정말 삭제하시겠습니까?",
    deleteWarning: "삭제된 기록은 복구할 수 없습니다.",
    cancel: "취소",
    delete: "삭제",
    errorTitle: "오류",
    errorRetry: "오류가 발생했습니다. 다시 시도해주세요.",
    confirm: "확인",

    /* 404 */
    pageNotFound: "PAGE NOT FOUND",
    notFoundMsg1: "이 페이지는 무용하지도 않습니다.",
    notFoundMsg2: "존재하지 않으니까요.",
    notFoundBack: "< 돌아가기",
    notFoundLabel: "대신, 누군가의 무용한 기록",

    /* Share */
    shareTitle: "무용한 기쁨",
    shareText: "나를 기쁘게 하는 아름답지만 무용한 것",
    downloadFileName: "pointless-joy",

    /* ArtPhase — 링크 복사 */
    linkCopy: "링크 복사",
    linkCopied: "복사 완료!",

    /* QuestionPhase — 동의 안내 */
    consentPrefix: "제출 시 ",
    termsOfService: "이용약관",
    consentAnd: " 및 ",
    privacyPolicy: "개인정보처리방침",
    consentSuffix: "에 동의합니다.",

    /* 관리자 모달 */
    adminPrompt: "관리자 암호를 입력하세요",
    adminWrongPassword: "암호가 올바르지 않습니다.",
    adminServerError: "서버 오류가 발생했습니다.",

    /* Card 랜딩 페이지 */
    cardCta: "나도 써보기 >",
    cardQuestion: "나를 기쁘게 하는 아름답지만 무용한 것은?",
  },
  en: {
    appTitle: "Pointless Joy",
    appDescription: "What is the beautiful but useless thing that brings me joy?",

    questionLine1: "What is the beautiful",
    questionLine2: "but useless thing",
    questionLine3: "that brings me joy?",
    answerPlaceholder: (n: number | null) =>
      n !== null ? `Write your ${n + 1}th thought...` : "Write your thought...",
    nicknamePlaceholder: "Enter your nickname",
    nicknameRandom: "Random",
    submit: "Start >",
    submitHint: "Ctrl+Enter to submit",
    tickerLabel: "Others' pointless joys",
    archive: "Archive",

    loading: "Writing thoughts",

    rewrite: "Write Again",
    share: "Share",
    aiDisclaimer: "This text was generated by AI based on your answer.",

    archiveLabel: "03 / ARCHIVE",
    archiveTitle1: "Archive of",
    archiveTitle2: "Pointless Things",
    records: (n: number) => `${n} RECORDS`,
    noRecords: "No records yet.",
    noRecordsHint: "Write your first answer.",
    firstRecord: "First Record >",
    newWrite: "+ New Write",
    goBack: "< Back",
    view: "View >",

    deleteConfirm: "Delete this record?",
    deleteWarning: "Deleted records cannot be recovered.",
    cancel: "Cancel",
    delete: "Delete",
    errorTitle: "Error",
    errorRetry: "An error occurred. Please try again.",
    confirm: "OK",

    pageNotFound: "PAGE NOT FOUND",
    notFoundMsg1: "This page isn't even useless.",
    notFoundMsg2: "It doesn't exist.",
    notFoundBack: "< Go Back",
    notFoundLabel: "Instead, someone's pointless record",

    shareTitle: "Pointless Joy",
    shareText: "The beautiful but useless thing that brings me joy",
    downloadFileName: "pointless-joy",

    linkCopy: "Copy Link",
    linkCopied: "Copied!",

    consentPrefix: "By submitting, you agree to our ",
    termsOfService: "Terms of Service",
    consentAnd: " and ",
    privacyPolicy: "Privacy Policy",
    consentSuffix: ".",

    adminPrompt: "Enter admin password",
    adminWrongPassword: "Incorrect password.",
    adminServerError: "Server error occurred.",

    cardCta: "Try It Yourself >",
    cardQuestion: "What is the beautiful but useless thing that brings me joy?",
  },
};

export type Dictionary = typeof dictionaries.ko;
